language: ruby
rvm:
- 2.5.0

before_install:
- gem update --system

install:
- bundle install
- npm install

script:
#- bundle exec rake spec:all
- bundle exec rspec spec/api/source/update_source_params_spec.rb 
