language: ruby
rvm:
- 2.5.1
- 2.6.1


before_install:
- gem update --system
- gem install -v 1.17.3 bundler --no-rdoc --no-ri

install:
- bundle install
- npm install

script:
- bundle exec rake

services:
  - redis-server
